title: Use a craft knife safely
hero_image: images/banner.png
description: Use a craft knife safely
version: 4
listed: false
copyedit: false
last_tested: "2022-02-17"
steps:
  - title: Use a craft knife safely
