title: Safe use of a craft knife
hero_image: images/banner.png
description: Safe use of a craft knife
version: 4
listed: false
copyedit: false
last_tested: "2022-02-17"
steps:
  - title: Safe use of a craft knife
